//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Is_Prokat_Sport_Invent.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserDataEntities1 : DbContext
    {
        private static UserDataEntities1 _context;
        public UserDataEntities1()
            : base("name=UserDataEntities1")
        {
        }
        
        public static UserDataEntities1 GetContext()
        {
            if (_context == null)
            {
                _context = new UserDataEntities1();
            }
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeVxoda> TypeVxoda { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
